### ISSUE TITLE
Remove 'ch' from unit-disallowed-list

### ISSUE THREAD

**Issue by hhsl** [fuhlig/stylelint-config-copilot#332]
According to [caniuse.com](caniuse.com):  'ch' is a 'Unit representing the width of the character "0" in the current font, of particular use in combination with monospace fonts'. And considering its [wide adoption](https://caniuse.com/ch-unit) across all browsers as well, could this unit be removed from the ruleset? :)

https://github.com/fuhlig/stylelint-config-copilot/blob/1eea794535775630b352c1328407fe251da76479/packages/stylelint-config-copilot-base/index.js#L250

**Comment by fuhlig** [comment]
Thanks for reporting :)

Released with `0.4.1`
https://www.npmjs.com/package/stylelint-config-copilot-base
