### ISSUE TITLE
Use peerDependencies in package.json

### ISSUE THREAD

**Issue by hhsl** [fuhlig/stylelint-config-copilot#371]
its a small thing, but due to the impending doom of dependency management of NPM Modules (e.g. when trying to use Yarn2's pnp thing), it might be better to use peerDependencies  for the stylelint copilot packages: 
https://github.com/fuhlig/stylelint-config-copilot/blob/28c67e68751f0fca46b76d787566722e89e9c8b5/packages/stylelint-config-copilot-base/package.json#L21

NPM-Documention https://docs.npmjs.com/cli/v6/configuring-npm/package-json#peerdependencies

Might be worth the consideration :)

**Comment by fuhlig** [comment]
Will take a look, thanks for the heads up

**Comment by fuhlig** [comment]
https://github.com/fuhlig/stylelint-config-copilot/commit/48f4975431de8db1031ea7ecd2c2e10691e9a91a
