### ISSUE TITLE
Support Stylelint 14: the function-calc-no-invalid rule was removed

### ISSUE THREAD

**Issue by hhsl** [fuhlig/stylelint-config-copilot#523]
The function-calc-no-invalid has been removed. You should remove it from your configuration object. https://stylelint.io/migration-guide/to-14#function-calc-no-invalid-rule

**Comment by fuhlig** [comment]
fixed with https://github.com/fuhlig/stylelint-config-copilot/commit/b4e56fccdd797303bb4406b679d4d6ddc18c41d4 and released with `1.0.0-rc.1`
